### ISSUE TITLE
只能认出来局域网的IP怎么办

### ISSUE THREAD

**Issue by niu12503** [QIN2DIM/hy2#5]
2023-09-11 17:18:23,638 - ERROR - 域名不可达或拼写错误的域名 - domain=xxx.xyz
2023-09-11 17:18:23,638 - ERROR - 你的主机外网IP与域名解析到的IP不一致 - my_ip=10.0.0.133 domain=xxx.xyz server_ip=

只能认出来局域网的IP怎么办

**Comment by QIN2DIM** [comment]
server_ipv4 是准的不

**Comment by QIN2DIM** [comment]
没有更多系统信息的话，我只能帮你算一卦了

```markdown
对于获取本地机器的公网IP,使用socket模块连接外网地址是一个常见的方法。但其实质是创建一个UDP连接,获取本机与目标地址间的源IP。

为什么在某些VPS上获取不到公网IP的原因可能有:

1. 该VPS没有分配公网IP,只有内网IP。这种情况下需要检查VPS的网络配置。

2. VPS启用了防火墙/安全组等,屏蔽了对外UDP连接。可以检查VPS的网络安全设置。

3. 该VPS处于双NAT之后,外网看不到实际机器的IP。这种情况下可以求助供应商检查网络拓扑。

4. 本地路由设置不正确,默认路由不是指向公网网关。可以检查本地路由表。

5. 代码使用了错误的网络接口。可以打印出连接结果,检查s.getsockname()返回的地址。

6. 目标地址不可达,连接失败。可以换成其他公网IP测试。

改进方法:

1. 添加超时时间,避免连接卡住

2. 多次请求不同公网地址,防止单点失败

3. 检查连接结果,如果不是公网IP,可打印提示信息

4. 获取本机所有地址,过滤出公网IP

5. 检查路由表确定默认网关,指定连接的网络接口

6. 在云平台上根据实例元数据来判断公网IP

总之,获取公网IP这个需求,需要考虑VPS的网络环境、本地网络配置、路由设置等多方面因素,有多种改进方法可以使结果更可靠。
```

**Comment by niu12503** [comment]
![image](https://github.com/QIN2DIM/hy2/assets/21340487/dacd23e7-d94c-439b-b7cc-6d278226e180)
用的是甲骨文的服务器，有公网IP，但是不能识别

**Comment by QIN2DIM** [comment]
神奇- -

跑一下这个看看 `curl ifconfig.me`

**Comment by QIN2DIM** [comment]
实在不行我加个 input 函数吧，虚拟化实例的网卡信息本身就是个挺抽象的东西- -

**Comment by niu12503** [comment]
![image](https://github.com/QIN2DIM/hy2/assets/21340487/4018176e-66d7-41a5-bb96-8b66f84315ec)

**Comment by QIN2DIM** [comment]
@niu12503 那个 13x.xxx 的应该就是- -

**Comment by QIN2DIM** [comment]
行这应该是个BUG，KVM 的网卡有很多种缝合形式，我测试的 VPS 刚好都是同一种

**Comment by niu12503** [comment]
> 试一下这个 @niu12503
> 
> ```shell
> python3 <(curl -fsSL https://raw.githubusercontent.com/QIN2DIM/hy2/parse-ipv4/heyhy.py) install -d 
> ```

谢谢，可以了
